name: Release & Publish

on:
  push:
    branches:
      - main
      - next
# on:
#   workflow_dispatch:
#     inputs:
#       dry_run:
#         description: 'Set to true to run a dry-run (no tags, no publishes)'
#         required: false
#         default: 'true'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for tags
      packages: write # for npm publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js & Authenticate to npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish @next
        if: github.ref == github.ref == 'refs/heads/next'
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @latest
        if: github.ref == 'refs/heads/main'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
